# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f7590690bf3efb02fbae536c9a9e3c8f19725bd0921a22881ee315f961cce711868d96092b2738f9ae7a3e077e21945200508969294fcdd665ea334c7b78f93

test:
  secret_key_base: 5a92c08dbc75a304f19834a028a8959eb6c09dec3fe8a10dbb8dad86c15e6daaa57a397dd8c76e9d3ab6a99e923a277599dc179b6802adea939bc610441d19b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
